version: '3'
services:
  aprsc:
    image: ghcr.io/vntgcode/aprsc-docker:2.1.21
    ports:
      - 8080:8080
      - 10152:10152
      - 14501:14501
      - 14580:14580
    security_opt:
      - no-new-privileges:true
    environment:
      - APRSC_SERVER_ID=MYCALL
      - APRSC_PASSCODE=MYAPRSCODE
      - APRSC_UPLINK_ENABLED=yes
      - APRSC_MY_ADMIN=My Name, My Call
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 64M