name: Build and Push
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

env:
  APRSC_VERSION: "2.1.21"
  BUILD_REV: "1" # Bump this when updating OS / base packages without changing APRSC_VERSION

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: myregistry/aprsc
          tags: |
            type=raw,value=${{ env.APRSC_VERSION }}-r${{ env.BUILD_REV }}
            type=raw,value=${{ env.APRSC_VERSION }}
            type=raw,value=2.1
            type=raw,value=latest

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            APRSC_VERSION=${{ env.APRSC_VERSION }}